name: Publish

on:
  workflow_dispatch:
    inputs:
      workshopid:
        type: choice
        description: 'Options: Main Branch, Dev Branch'
        options:
        - 2912941775 #main branch
        - 2913672477 #dev branch

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3.3.0

    - name: Increment version locally
      run: chmod +x ./tools/incrementVersion.js &&
        node ./tools/incrementVersion.js -b ${{github.sha}}

    - name: Build addons
      run: '.\tools\Builder\buildAddons.ps1 -WorkshopID ${{github.event.inputs.workshopid}}'

    - name: Upload build addon artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: A3A-Plus
        path: build\A3A-Plus
  # upload:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: [build]
  #   steps:
  #   - name: Download addon artifact
  #     uses: actions/download-artifact@v3.0.2
  #     with:
  #       name: A3A-Plus
  #       path: A3A-Plus

  #   - name: Publish to Steam Workshop
  #     uses: arma-actions/workshop-upload@v1.0.2
  #     with:
  #       appId: '107410'      # default
  #       itemId: ${{github.event.inputs.workshopid}} # https://steamcommunity.com/sharedfiles/filedetails/?id=[...]]
  #       contentPath: 'A3A-Plus'
  #       changelog: '[url=https://github.com/igorkis-scrts/A3-Antistasi-Plus/blob/master/ForkChangelog.md]Changelog[/url].'
  #     env:
  #       STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
  #       STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
